# Celestica Midstone-200i platform modules

CEL_200I_PLATFORM_MODULE_VERSION = 0.2.2

export CEL_200I_PLATFORM_MODULE_VERSION

CEL_200I_PLATFORM_MODULE = platform-modules-200i_$(CEL_200I_PLATFORM_MODULE_VERSION)_amd64.deb
$(CEL_200I_PLATFORM_MODULE)_SRC_PATH = $(PLATFORM_PATH)/sonic-platform-modules-cel
$(CEL_200I_PLATFORM_MODULE)_DEPENDS += $(LINUX_HEADERS) $(LINUX_HEADERS_COMMON)
$(CEL_200I_PLATFORM_MODULE)_PLATFORM = x86_64-cel_midstone-r0
SONIC_DPKG_DEBS += $(CEL_200I_PLATFORM_MODULE)
SONIC_STRETCH_DEBS+= $(CEL_200I_PLATFORM_MODULE)
